### ISSUE TITLE
Able to sign PDFS with a trailer but NOT able to sign PDFs without a trailer

### ISSUE THREAD

**Issue by mayurchoksi** [vbuch/node-signpdf#81]
**Describe the bug and the expected behaviour**
I have a few PDFs that don't contain a trailer.
It seems that PDFs with/without trailers are valid PDFs.

When I try to sign PDFs without a trailer using node-signpdf I get the following error:
(node:51815) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'split' of undefined
    at getXref (/Users/folderX/node_modules/node-signpdf/dist/helpers/plainAddPlaceholder/readRefTable.js:55:34)
    at getFullXrefTable (/Users/folderX/node_modules/node-signpdf/dist/helpers/plainAddPlaceholder/readRefTable.js:79:25)
    at readRefTable (/Users/folderX/node_modules/node-signpdf/dist/helpers/plainAddPlaceholder/readRefTable.js:100:25)
    at readPdf (/Users/folderX/node_modules/node-signpdf/dist/helpers/plainAddPlaceholder/readPdf.js:31:46)
    at plainAddPlaceholder (/Users/folderX/node_modules/node-signpdf/dist/helpers/plainAddPlaceholder/index.js:54:37)

I am using version the following versions:
    "node-forge": "^0.9.1",
    "node-signpdf": "^1.2.3",

Sample code attached.
[index.txt](https://github.com/vbuch/node-signpdf/files/4792243/index.txt)

**Comment by ghoshpushpendu** [comment]
this issue occurs when you are using PDF-Lib to add or parse the PDF before the signing process.

{ useObjectStreams: false } to the save() method did the trick! in pdf-lib
